### ISSUE TITLE
Support removal of certificates

### ISSUE THREAD

**Issue by aneagoe** [chef-cookbooks/trusted_certificate#13]
### Cookbook version
3.1.1

### Chef-client version
14.0.190

### Platform Details
CentOS Linux release 7.4.1708 (Core)

### Scenario:
It would be good to have a way to retire trusted CAs as well and the functionality could be easily implemented. If cookbook is used to deploy particular CAs it should be able to fully lifecycle them.

**Comment by tas50** [comment]
Added in 3.2.0
