### ISSUE TITLE
typo in `lib/matchers.rb`

### ISSUE THREAD

**Issue by sandervanburken** [chef-cookbooks/trusted_certificate#4]
In `/lib/matchers.rb` 'certificate' is written as 'certicate'. This typo renders the spec test unusable.
### Cookbook version

1.0.0
### Chef-client version

12.13.37
### Platform Details

Ubuntu 14.04
### Scenario:

Testing the `trusted_certificate` resource with chefspec.
### Steps to Reproduce:

Add a `trusted_certificate` resource to a recipe and add the spec test: `create_trusted_certificate`.
### Expected Result:

Test should pass.
### Actual Result:

`NoMethodError`

**Comment by tas50** [comment]
Oops. Fixed in 1.0.1
