### ISSUE TITLE
Resource idempotent?

### ISSUE THREAD

**Issue by holmesb** [chef-cookbooks/trusted_certificate#5]
### Cookbook version
commit [67ad4501d1f17a571ea2c86829a330188b4ba1d5] Oct 23, 2016

### Chef-client version
12.16.42

### Platform Details
Ubuntu 14.04

### Scenario:
Achieve idemotency

### Steps to Reproduce:
Add certificate using this resource

### Expected Result:
If certificate already exists, shouldn't run.

### Actual Result:
Certificate is installed upon every convergence.

**Comment by tas50** [comment]
Thanks for the report. I've fixed this in the 3.1.1 release.
